# Site settings
title: Day In Life of Nate
header-img: img/home-bg.jpg
# email: your-email@yourdomain.com
description: "Life as a Makersquare Student. Cohort MKS23 LA"
baseurl: "/blog"
# url: "http://yourdomain.com"
# twitter_username: SBootstrap
# github_username:  davidtmiller
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
